-- ŞEHİRLER TABLOSU
CREATE TABLE Sehirler_Tablosu (
    Plaka_Kodu SMALLINT PRIMARY KEY,
    Sehir_Adi VARCHAR(50) NOT NULL
);

-- HASTA BİLGİLERİ TABLOSU
CREATE TABLE Hasta_Bilgileri( 
    Hasta_Id SERIAL PRIMARY KEY,
    Ad VARCHAR(30) NOT NULL,
    Soyad VARCHAR(30) NOT NULL,
    TC VARCHAR(11) UNIQUE,
    Pasaport_No VARCHAR(20) UNIQUE,
    Cinsiyet VARCHAR(15),
    Dogum_Tarihi TIMESTAMP NOT NULL,
    E_Mail VARCHAR(100),
    Adresi VARCHAR(100) NOT NULL,
    Memleketi_Plaka_Kodu SMALLINT,
    Dogum_Yeri_Plaka_Kodu SMALLINT,
    Hasta_Telefon_No VARCHAR(20),
    Hasta_Yakini_Adi VARCHAR(30),
    Hasta_Yakini_Soyadi VARCHAR(30),
    Hasta_Yakini_Neyi VARCHAR(20),
    Hasta_Yakini_Telefon_No VARCHAR(20),
    Hastalik_Tanisi VARCHAR(300),
    Kilo_Kg DECIMAL,
    Boy_Cm DECIMAL,
    Ayak_No DECIMAL,
    Kalca_Diz_Mesafesi DECIMAL,
    Diz_Topuk_Mesafesi DECIMAL,
    Kayit_Tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Guncelleme_Tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Aktif_Pasif_Durumu VARCHAR(10),

    -- KOŞULLAR
    CONSTRAINT TC_PS CHECK (TC IS NOT NULL OR Pasaport_No IS NOT NULL),
    CONSTRAINT chk_cinsiyet CHECK (Cinsiyet IN ('Kadın', 'Erkek', 'Belirtmek İstemiyorum')),
    CONSTRAINT TEL1_TEL2 CHECK (Hasta_Telefon_No IS NOT NULL OR Hasta_Yakini_Telefon_No IS NOT NULL),
    CONSTRAINT Akt_Pas CHECK (Aktif_Pasif_Durumu IN ('Aktif', 'Pasif')),

    -- YABANCI ANAHTARLAR
    CONSTRAINT fk_memleket FOREIGN KEY (Memleketi_Plaka_Kodu)
        REFERENCES Sehirler_Tablosu (Plaka_Kodu)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT fk_dogum_yeri FOREIGN KEY (Dogum_Yeri_Plaka_Kodu)
        REFERENCES Sehirler_Tablosu (Plaka_Kodu)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- KULLANICILAR TABLOSU
CREATE TABLE Kullanicilar_Tablosu(
    Kullanici_Adi_Soyadi VARCHAR(100) NOT NULL,
    Sifre_Hash VARCHAR(255) NOT NULL,
    TC VARCHAR(11),
    Pasaport_No VARCHAR(20),
    Cinsiyet VARCHAR(15),
    Rol VARCHAR(10) NOT NULL,
    E_Posta VARCHAR(320),
    Telefon VARCHAR(15) NOT NULL,
    Kayit_Tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Son_Giris_Tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Aktif_Pasif_Durumu VARCHAR(5) NOT NULL,
    CONSTRAINT chk_cinsiyet_kullanici CHECK (Cinsiyet IN ('Kadın', 'Erkek', 'Belirtmek İstemiyorum')),
    CONSTRAINT chk_aktif_pasif CHECK (Aktif_Pasif_Durumu IN ('Aktif','Pasif'))
);

-- ŞEHİRLER VERİLERİ
INSERT INTO Sehirler_Tablosu (Plaka_Kodu, Sehir_Adi) VALUES
(1, 'Adana'),
(2, 'Adıyaman'),
(3, 'Afyonkarahisar'),
(4, 'Ağrı'),
(5, 'Amasya'),
(6, 'Ankara'),
(7, 'Antalya'),
(8, 'Artvin'),
(9, 'Aydın'),
(10, 'Balıkesir'),
(11, 'Bilecik'),
(12, 'Bingöl'),
(13, 'Bitlis'),
(14, 'Bolu'),
(15, 'Burdur'),
(16, 'Bursa'),
(17, 'Çanakkale'),
(18, 'Çankırı'),
(19, 'Çorum'),
(20, 'Denizli'),
(21, 'Diyarbakır'),
(22, 'Edirne'),
(23, 'Elazığ'),
(24, 'Erzincan'),
(25, 'Erzurum'),
(26, 'Eskişehir'),
(27, 'Gaziantep'),
(28, 'Giresun'),
(29, 'Gümüşhane'),
(30, 'Hakkari'),
(31, 'Hatay'),
(32, 'Isparta'),
(33, 'Mersin'),
(34, 'İstanbul'),
(35, 'İzmir'),
(36, 'Kars'),
(37, 'Kastamonu'),
(38, 'Kayseri'),
(39, 'Kırklareli'),
(40, 'Kırşehir'),
(41, 'Kocaeli'),
(42, 'Konya'),
(43, 'Kütahya'),
(44, 'Malatya'),
(45, 'Manisa'),
(46, 'Kahramanmaraş'),
(47, 'Mardin'),
(48, 'Muğla'),
(49, 'Muş'),
(50, 'Nevşehir'),
(51, 'Niğde'),
(52, 'Ordu'),
(53, 'Rize'),
(54, 'Sakarya'),
(55, 'Samsun'),
(56, 'Siirt'),
(57, 'Sinop'),
(58, 'Sivas'),
(59, 'Tekirdağ'),
(60, 'Tokat'),
(61, 'Trabzon'),
(62, 'Tunceli'),
(63, 'Şanlıurfa'),
(64, 'Uşak'),
(65, 'Van'),
(66, 'Yozgat'),
(67, 'Zonguldak'),
(68, 'Aksaray'),
(69, 'Bayburt'),
(70, 'Karaman'),
(71, 'Kırıkkale'),
(72, 'Batman'),
(73, 'Şırnak'),
(74, 'Bartın'),
(75, 'Ardahan'),
(76, 'Iğdır'),
(77, 'Yalova'),
(78, 'Karabük'),
(79, 'Kilis'),
(80, 'Osmaniye'),
(81, 'Düzce');
